### ISSUE TITLE
Scraping data

### ISSUE THREAD

**Issue by alinazeng** [lizzieinvancouver/localadaptclim#1]
Hi Lizzie,
@lizzieinvancouver 

I uploaded several papers to this [google drive folder ](https://drive.google.com/drive/folders/1wzTWgPlaD2FZzd3WptarfUsJZlhfuCAL) for you to have a look and see if there are any saving graces. One thing I am unsure about is that given the points are all black and of the same shape, even we digitize them we still would not know which provenance they correspond to... Let me know what you think.

Thank you!

**Comment by lizzieinvancouver** [comment]
@alinazeng Thanks! There's definitely some next steps for most of these:

- Ducousso 1995 -- this paper is confusing, there's no easy data to gather.
- Hall et al 2007 -- it looks like we can scrape some of the data we need in figure 3. Unfortunately it doesn't look like we can match the populations directly to a location (just a latitude) so we could never get local climate data, but we could at least compare the strength of the cline in North America versus Europe with these data. I suggest we also email the author to request the location data for the populations.
- Kremer et al 2014 -- appears to be a review of other papers, right? Then the next step would be to check those papers directly. I see there's some data by altitude but it's best to get it directly from the original paper.
- Rosique-Esplugas et al 2021 -- looks Figure 4 has some of the data we want (phenology by latitude) and I think the supp table gives all the population locations (this is also a more recent paper, and more recently folks try to share or publish data -- so check all the links before the supp to see if they just posted the data somewhere). 
- Savolainen et al 2007 -- check out papers referenced in Figure 3 to see if they have the data (or figures we can scrape data from). 
- Liu El-Kassaby 2019 -- this paper mentions data posted on Dryad (a common data server). You should try to track it down, if you can't, then contact the Dryad team (and then contact the corresponding author, email given on the first page of article).

**Comment by lizzieinvancouver** [comment]
@alinazeng Right now I don't think you need to scrape any data, but you can start reading up on it... check out the mp4 here:
[https://github.com/lizzieinvancouver/ospree/tree/master/notes/howtoscrape](https://github.com/lizzieinvancouver/ospree/tree/master/notes/howtoscrape)

**Comment by alinazeng** [comment]
Hi lizzie @lizzieinvancouver  sounds good. I will revisit them and see what I can do. 
Will draft a few emails and have you proofread next week if we in fact do need to reach out to the authors

Kremer et al 2014 used the data from [Alberto et al 2011](https://github.com/lizzieinvancouver/localadaptclim/blob/main/data/journal_articles_sourced_from_Alberto2013/Alberto%20et%20al.%202011.pdf) and it looks mostly at altitudinal effects...

Thanks for sharing the mp4!

**Comment by alinazeng** [comment]
@lizzieinvancouver Hi Lizzie, here is a follow-up:

- Rosique-Esplugas et al 2021  --- Yes I was able to obtain information for each provenance and doy
- Liu & El-Kassaby 2019  --- the data cannot be found on Dyrad due to the link being broken. I drafted an email and let me know if/when you would like me to send this:

> Dear Dr. Liu,
> 
> Hope you are well!
> My name is Alina and I am an undergrad student in Dr. Elizabeth Wolkovich's (cc'd) Temporal Ecology Lab at UBC. 
> 
> We are interested in carrying out a meta-analysis on local adaptation and phenological plasticity and came across your 2019 paper "Phenotypic plasticity of natural Populus trichocarpa populations in response to temporally environmental change in a common garden." We understand that the original data for this paper has been made available at Dryad Digital Repository (https://doi.org/10.5061/dryad.02v6wwq00), however, the DOI seems to be malfunctioning. 
> 
> Could you kindly provide us with the data for this paper if it is not too much trouble for you? We are particularly interested in the day of year for spring events (bud break). Thank you very much for your patience and kindness and we look forward to hearing from you.
> 
> Best,
> Alina

- Regarding Hall et al 2007, we should definitely reach out to the authors for location information. However, it feels more appropriate if you email them (given they are not UBC folks). Please let me know and thank you!

**Comment by lizzieinvancouver** [comment]
@alinazeng Email looks good -- please send it!

And, yes, I can email Hall. Can you draft an email in the format of the above and email to me with the email address? I will send it and BCC you.

Thanks!

**Comment by lizzieinvancouver** [comment]
Eventually we want data formatted as columns with

- elevation of garden
- latitude of garden
- longitude of garden 
- elevation of source population
- latitude of source population
- longitude of source population
- species
- day of year
- year (of observation) if given
