### ISSUE TITLE
finalizing methods for the ms: didn't we try other search terms?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/localadaptclim#22]
@alinazeng I am sure we have had some back and forth about checking other search terms...  but I cannot find it in the Rnw or the issues (I may not be looking well enough). Can you remind me of what we discussed and where we're at now? I know you said you would try some additional search terms and we should make a note here of that so we remember. 

See also issue #18.

**Comment by alinazeng** [comment]
@lizzieinvancouver 

I think our search terms have always been what's already included in the ms.

TOPIC = (common garden* OR provenance*) AND (leafout* OR leaf out* OR budburst OR spring phenolog*

Aside from reading the returned papers, I also looked at papers they cited, and other related papers to ensure we didn't miss things.

**Comment by lizzieinvancouver** [comment]
@alinazeng Okay, I must be remembering something else then. If you can double check for any notes in my Rnw comments or in emails, that would be great. If you find any notes -- add them here. If you don't also make a note here and you can close this issue.

**Comment by alinazeng** [comment]
closing this issue since we haven't really searched other terms.

**Comment by lizzieinvancouver** [comment]
@alinazeng My notes in the Rnw from Jan 24 include something about this ... if you look at [the commit](https://github.com/lizzieinvancouver/localadaptclim/commit/49ccf53864217b0ef72906969084793bb52bae2f) you'll see that you used to say we searched TITLE, not topic. Can you please double-check this search as based on TOPIC and not TITLE?

**Comment by alinazeng** [comment]
@lizzieinvancouver 
Ohhhhh that's what you meant!! I misunderstood. I thought by "other search terms" you meant the different variations of budburst, leaf flush, etc. 

If we are talking about TOPIC vs TITLE then yes I tried both. Will add to the issue in a bit.

**Comment by lizzieinvancouver** [comment]
@alinazeng Great! Once you add it go ahead and close this again. Thanks.

**Comment by alinazeng** [comment]
Dug out screenshot of my search on in December 2022. 

Our latest search is indeed TOPIC = (common garden* OR provenance*) AND (leafout* OR leaf out* OR budburst OR spring phenolog*

Have attempted TITLE = (common garden* OR provenance*) AND (leafout* OR leaf out* OR budburst OR spring phenolog* but it only returns 15 results, all of which are already captured by the search where we used TOPIC
