### ISSUE TITLE
loop to extract climate data

### ISSUE THREAD

**Issue by alinazeng** [lizzieinvancouver/localadaptclim#9]

**Comment by alinazeng** [comment]
Hi lizzie. @lizzieinvancouver 

I have organized my current code into this [script:](https://github.com/lizzieinvancouver/localadaptclim/blob/main/Analyses/script_for_lizzie_to_make_loop.R)

thank you very much for your help! there is no rush.

**Comment by lizzieinvancouver** [comment]
@alinazeng I made some rough edits in [this commit](https://github.com/lizzieinvancouver/localadaptclim/commit/d2685525e439dd966f3b58cf6451d0388b3e3c00) ... but I did not have time to download the climate data, so you'll have to make some edits to get it to work. Let me know how it goes!
